apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 80;
        location / {
          add_header Content-Type text/plain;
          return 200 'Hello from k8s';
        }
      }
    }